SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{691AF5A390263338}" {
   m_sCallsign "BFA"
  }
 }
 m_aPlatoonNames {
  SCR_CallsignInfo "{691AF5A390278E86}" {
   m_sCallsign "Arrow"
  }
  SCR_CallsignInfo "{691AF5A390278E87}" {
   m_sCallsign "Bastion"
  }
  SCR_CallsignInfo "{691AF5A390278E80}" {
   m_sCallsign "Cinder"
  }
  SCR_CallsignInfo "{691AF5A390278E81}" {
   m_sCallsign "Dog"
  }
  SCR_CallsignInfo "{6920F35620A06FC5}" {
   m_sCallsign "Errant"
  }
  SCR_CallsignInfo "{6920F356209047EE}" {
   m_sCallsign "Falcon"
  }
  SCR_CallsignInfo "{6920F35620FD45DC}" {
   m_sCallsign "Mechanicus"
  }
  SCR_CallsignInfo "{6920F35621287241}" {
   m_sCallsign "Command"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{691AF5A39027AB3E}" {
   m_sCallsign "Group"
  }
 }
 m_sCallsignGroupFormat "%1 %2 %3"
 m_sCallsignCharacterFormat "%1 %2 %3: %4"
 m_sCallsignCharacterWithRoleFormat "%1 %2 %3: %4"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{691AF5A39027ABEE}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{691AF5A39027ABED}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{691AF5A39027ABEC}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}