SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{691AF5A390263338}" {
   m_sCallsign "Battlegroup Arrow - 212th and 23rd Cadian"
  }
  SCR_CallsignInfo "{691AF5A23E21D1D3}" {
   m_sCallsign "Battlegroup Bastion - 741st Krieg"
  }
  SCR_CallsignInfo "{691AF5A200B18331}" {
   m_sCallsign "Battlegroup Cinder -120th Steel Legion"
  }
  SCR_CallsignInfo "{691AF5A2055D523B}" {
   m_sCallsign "Battlegroup Dog - 310th Cadian Reserves"
  }
  SCR_CallsignInfo "{691AF5A20FEC33CB}" {
   m_sCallsign "Battlegroup Errant - 210th Shock Corps"
  }
  SCR_CallsignInfo "{691AF5A2114F65E5}" {
   m_sCallsign "Falcon Squadron - 5082nd Naval Wing"
  }
  SCR_CallsignInfo "{691AF5A253CE2773}" {
   m_sCallsign "Adeptus Mechanicus"
  }
 }
 m_aPlatoonNames {
  SCR_CallsignInfo "{691AF5A390278E86}" {
   m_sCallsign "Red"
  }
  SCR_CallsignInfo "{691AF5A390278E87}" {
   m_sCallsign "Blue"
  }
  SCR_CallsignInfo "{691AF5A390278E80}" {
   m_sCallsign "Yellow"
  }
  SCR_CallsignInfo "{691AF5A390278E81}" {
   m_sCallsign "Green"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{691AF5A39027AB3E}" {
   m_sCallsign "1"
  }
  SCR_CallsignInfo "{691AF5A39027ABE9}" {
   m_sCallsign "2"
  }
  SCR_CallsignInfo "{691AF5A39027ABE8}" {
   m_sCallsign "3"
  }
  SCR_CallsignInfo "{691AF5A39027ABEF}" {
   m_sCallsign "4"
  }
 }
 m_sCallsignGroupFormat "%1 %2 %3"
 m_sCallsignCharacterFormat "%1 %2 %3: %4"
 m_sCallsignCharacterWithRoleFormat "%1 %2 %3: %4"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{691AF5A39027ABEE}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{691AF5A39027ABED}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{691AF5A39027ABEC}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}