SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{69192A644F813D53}" {
   m_sEntityPrefab "{20DC22C7D62229FF}Prefabs/Characters/Factions/BLUFOR/BFV/Character_BFA_Conscript.et"
  }
  SCR_EntityCatalogEntry "{691AFD41490C8033}" {
   m_sEntityPrefab "{22A02D3251ED2851}Prefabs/Characters/Factions/BLUFOR/BFV/Character_BFA_Recruit.et"
  }
 }
}