SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{69192A644F813D53}" {
   m_sEntityPrefab "{20DC22C7D62229FF}Prefabs/Characters/Factions/BLUFOR/BFV/Character_BFV_Conscript.et"
  }
 }
}