SCR_FactionHomeTerritoryConfig {
 m_aFactionHomeTerritories {
  SCR_FactionHomeTerritory "{6918DDC4825FE023}" {
   m_sID "Terra"
   m_UIInfo SCR_UIInfo "{6918DDC486ECE39F}" {
    Name "Terra"
   }
  }
  SCR_FactionHomeTerritory "{6918DDC495EA3BE9}" {
   m_sID "Armageddon"
   m_UIInfo SCR_UIInfo "{6918DDC4E71C7DDB}" {
    Name "Armageddon"
   }
  }
  SCR_FactionHomeTerritory "{6918DDC4EB9D0B0B}" {
   m_sID "Cadia"
   m_UIInfo SCR_UIInfo "{6918DDC4EEC32566}" {
    Name "Cadia"
   }
  }
  SCR_FactionHomeTerritory "{6918DDC4F0D6EFAB}" {
   m_sID "Krieg"
   m_UIInfo SCR_UIInfo "{6918DDC4FA75487A}" {
    Name "Krieg"
   }
  }
  SCR_FactionHomeTerritory "{6918DDC4F988307F}" {
   m_sID "Mars"
   m_UIInfo SCR_UIInfo "{6918DDC4C28E0DBB}" {
    Name "Mars"
   }
  }
 }
 m_fSharedPlaceOfBirthWeight 0.6
}