SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{6918DDC76AAA763F}" {
   m_Info SCR_UIInfo "{6918DDC770B8AF77}" {
    Name "Battle Fleet Armageddon"
    Icon "{2BA195AE60A24B06}UI/Flags/Imperium/BFA_Flag_01.edds"
   }
   m_LabelType FACTION_BFA
   m_LabelGroupType FACTION
  }
 }
}